# Generated by Django 4.1.3 on 2022-11-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.CharField(choices=[('5', '5%'), ('10', '10%'), ('15', '15%'), ('25', '25%')], max_length=3),
        ),
    ]
